### ISSUE TITLE
The sea

### ISSUE THREAD

**Issue by pedro-w** [grrk-bzzt/kq-fork#138]
Despite me moaning about running out of time and needing to focus, the sea tile on the world map has always bugged me. I made a more subtle version, what do you think? It still jumps about a bit, there are a couple of pixels need tweaking still (I am really bad at graphics!)
![sea-old](https://user-images.githubusercontent.com/22172519/184536024-dc3be46b-d155-491b-b3d6-920e6edca65d.gif)
![sea-new](https://user-images.githubusercontent.com/22172519/184536028-f71511ac-5f8b-4414-9431-821d18971e3b.gif)

**Comment by OnlineCop** [comment]
First: Sorry for the lack of updates and feedback this last week. 2x 40-hour jobs + family needs took its toll.

Second: So. Much. Yes. I really love the change for the more subtle waves. I'm all for approving this if you were to make it a PR; or, you can just merge it straight in since it doesn't appear to be a code change.

**Comment by pedro-w** [comment]
I didn't know there were that many hours in the week 😫 Hope you find some time to relax soon.

Yes, it's literally just editing those four tiles in `land.png`, no code.

**Comment by pedro-w** [comment]
OK , done in 49786d348ac3081cf7961fdda700e18ffef1a0e7
