### ISSUE TITLE
Original KQ webpage wiki is back up

### ISSUE THREAD

**Issue by OnlineCop** [grrk-bzzt/kq-fork#29]
The http://kqlives.sourceforge.net wiki has been updated to *kinda* work, although many features (LikePages, BackLinks) are not functional.  There is almost no login authentication, which means that it might be easily vandalized.

Bu-u-u-ut... should we link it to this project (or this project back to it)?  It can be used as a reference for people wanting to contribute, or just to figure out what was happening in the (unfinished) storyline.

**Comment by peterhull90** [comment]
Is there some way in PhpWiki to produce a static dump of all the pages? That could then be imported to the gh-pages of this repository. At least the info would be 'safe' then.

**Comment by OnlineCop** [comment]
Looks like the website-based wiki is gone. SourceForge went down for, what was it, a week? Unless someone knows where the data was, it looks like this information is lost or inaccessible at this point.

**Comment by peterhull90** [comment]
I'm pretty sure SF are planning to bring everything back up as it was (this last week must have been a PR disaster for them)... anyway I have a file called KqLivesFullBackup2005.zip, which has the text of the web pages, but no images. It might be useful to reconstruct the wiki.

I also have a database backup from 2010 which ought to be complete if I could get an instance of PhpWiki running again.

**Comment by peterhull90** [comment]
Folks, I've converted the PhpWiki page dump to (sort-of) markdown and put it on my gh-pages branch

http://peterhull90.github.io/kq-fork/

The data is basically there and I was able to convert PhpWiki's revisions to dated git commits but there are some issues with encoding (particularly apostrophes have come out as weird UTF-8 things) which I don't understand. Also, I've made no effort with the page templates and css, though I'm running everything through Jekyll so it will be easy to apply a style to the pages.

Would be good if this can be pulled into the main repo, unfortunately I can't put in a pull request because the main repo doesn't have a gh-pages branch to select as the target.
