### ISSUE TITLE
While entering caves or buildings with a partner sometimes the partner goes out of bounds causing a seg fault.

### ISSUE THREAD

**Issue by z9484** [grrk-bzzt/kq-fork#81]
While entering caves or buildings with a partner sometimes the partner goes out of bounds and causes the game to crash.
It crashes on line Entity.cpp:622 with an out of bound error. dest_x is a very large negative number e.g. -65282.
This happens often when the warp to position is near the bottom of the map.

**Comment by pedro-w** [comment]
Just to save time, can you name a map where this happens? And, does 'sometimes' mean some warps do and some don't, or the same one sometimes crashes and sometimes doesn't? My guess is that move_x becomes something that is not -1, 0, or 1 in the call to `obstruction()`.

**Comment by OnlineCop** [comment]
I'm looking into this currently. It appears that the culprit is the use of C memory management (`memcpy()`, `memmove()`, `malloc()`, `calloc()`) on objects that use C++ constructors/destructors.

There are a few POD structs (plain old data; no C++ constructors/destructors or `std::string` or anything) such as `KQEntity g_ent[MAX_ENTITIES]` and others that are getting their memory corrupted due to the blended use of the C++ and C-style memory management at the wrong times.

The change is fairly large, so I want to be extra careful and may need to test a variety of scenarios (probably making heavy use of the F11 cheat to add/remove party members, warp to the maps in question where you're seeing these bugs).

@z9484: do you have any screenshots or reproduction steps so I can narrow this down?
- Town in which this occurs?
- Doorway in which this occurs?
- Whether you're "running" or walking without holding down the run key?
- Whether the partner is right next to you, or has lagged slightly because you walked around an obstacle and it's trying to pathfind to you and is further away than it should?
- Whether you were moving straight up/down into the doorway or moving at a diagonal?

**Comment by z9484** [comment]
cave6a which main map 264,165, it happens walking or running.  Usually when you don't walk straight up.

![Screenshot 2022-06-17 142644](https://user-images.githubusercontent.com/87368/174396913-9d50bec1-9026-4c03-bece-9c19e1bf7813.png)

**Comment by z9484** [comment]
dest_x is -65461 in cave5 opal dragon cave left entrance
![Screenshot 2022-06-17 191129](https://user-images.githubusercontent.com/87368/174416775-5875e2b8-fca7-444f-b62a-3e37c4f04399.png)

**Comment by OnlineCop** [comment]
I think it's this block within src/movement.cpp:
```c++
    /*  RB: faster to do this than to check if there is an entity at every square
     */
    for (entity_index = 0; entity_index < MAX_ENTITIES; entity_index++)
    {
        if (g_ent[entity_index].active)
        {
            map[g_ent[entity_index].tilex * g_map.ysize + g_ent[entity_index].tiley] = -1;
        }
    }
```
That should be the entity's `tiley` multiplied by the map's `xsize`, plus the entity's `tilex` offset:
```c++
            map[g_ent[entity_index].tiley * g_map.xsize + g_ent[entity_index].tilex] = -1;
```

**Comment by pedro-w** [comment]
That's definitely a (long standing!) bug and the new/malloc/free/delete thing should be changed but I can't see how they cause the problem here.
On the other hand I've been in and out of that wretched cave5 a hundred times and not seen anything untoward 😞

**Comment by OnlineCop** [comment]
PR #104 should hopefully fix this issue, although it does shuffle quite a bit of code around.

My initial pass is to make an Entity manager which can update the entity movement calculations, although it leaves quite a few of the entity-related variables in their original global scope.

A second pass moves a lot of those global variables into the entity manager class, but leaves them public because of a few C-isms that won't allow me to just wrap them with getters/setters.

There's a lot of C-style memory management going on all over the place, and some of these structs are actually PODs (plain-old-data) which means that attempting to convert them to C++ with constructors/destructors actually dies spectacularly.

A third pass would protect these member variables and force usage via accessors (getters/setters). Then I'd be able to write an interface to the manager class so I can gmock/gtest the functionality to ensure everything works properly.
