### ISSUE TITLE
Not enough inventory for the opal armor

### ISSUE THREAD

**Issue by z9484** [grrk-bzzt/kq-fork#95]
As I was playing through I got to the point where you actually get the opal armor as items(not key items) and my inventory was full so it just said opal band not received. 

What should we do? 
* Simple 3x the Inventory space is currently 4 pages of inventory.
*  Make it endlessly expanding up to say like 99 pages
*  Just check to make sure you have room for the opal armor first. Downside of this approach is we might need to adjust chest logic as well to not count as opened if you don't receive it. There are some places I think in the scripts where items are added that it wouldn't catch but it should take care of most cases.

**Comment by pedro-w** [comment]
Interesting issue. Do you know what the upper bound is -  how many pages we would need if you picked up everything?

**Comment by z9484** [comment]
NUM_ITEMS is is equal to 192

**Comment by OnlineCop** [comment]
Each slot currently supports up to 9x of each item. Currently, to hold 18 Medicinal Herbs, you need 2 slots.

1. We could raise the limit to 99, but keep the hard "4 pages of inventory" that's imposed currently. That won't really fix the reported issue, but instead of taking multiple slots to hold enough items, it requires only 1 slot.
1. We can use a C++ vector to hold the inventory, and let it grow dynamically with no limit of number of pages.

With either of these approaches, we could also do what other games do and limit you to 1 slot per item type, meaning that once you hit your cap (be it 9 or 99), your bag won't accept any more of that item.

**Comment by pedro-w** [comment]
I've started on this, going for option 2 initially. Using a std::vector for g_inv works OK with a few changes, and also makes some of the algorithms simpler.

**Comment by OnlineCop** [comment]
Cool! While you’re adjusting that, could you move that vector into some class somewhere so it can be pulled out of the global scope?
